repos:

  - repo: https://github.com/pycqa/flake8

    rev: 7.1.2

    hooks:

      - id: flake8

        args:

          - "--max-line-length=1000"

          - "--extend-ignore=E501,E712,E302,E128,F405,W391,F541,F401,F811,E231,E722"

        name: flake8

#        language: system

        types: [python]
 
 
  - repo: https://github.com/psf/black

    rev: 23.1.0

    hooks:

      - id: black